all:
	@echo "see /usr/src/linux/Documentation/memory-barriers.txt"

target: dependencies
	# action lines or Make rules
	echo "<tab> rule that converts the dependency into target"
	# normally, all 3 .. target / dependency / action lines
	#

dependencies: Makefile
	#
